from __future__ import annotations

from ._pyglsim import (
    Entity,
    Registry,
    System,
    World,
    Vec2u,
    GpuContext,
    Window,
    RenderingSystem,
    PhysicsSystem,
    KeyCode,
    MouseButton,
    EventType,
    WindowResizeEvent,
    WindowMinimizeEvent,
    WindowCloseEvent,
    KeyPressEvent,
    KeyReleaseEvent,
    KeyTypeEvent,
    MouseMoveEvent,
    MouseScrollEvent,
    MousePressEvent,
    MouseReleaseEvent,
    subscribe_event,
    unsubscribe_event,
    Input,
)

__version__ = "0.1.0"
__doc__ = "High performance simulation engine."

__all__ = [
    "__doc__",
    "__version__",
    "Entity",
    "Registry",
    "System",
    "World",
    "Vec2u",
    "GpuContext",
    "Window",
    "RenderingSystem",
    "PhysicsSystem",
    "KeyCode",
    "MouseButton",
    "EventType",
    "WindowResizeEvent",
    "WindowMinimizeEvent",
    "WindowCloseEvent",
    "KeyPressEvent",
    "KeyReleaseEvent",
    "KeyTypeEvent",
    "MouseMoveEvent",
    "MouseScrollEvent",
    "MousePressEvent",
    "MouseReleaseEvent",
    "subscribe_event",
    "unsubscribe_event",
    "Input",
]
